apiVersion: apps/v1
kind: Deployment

metadata:
  name: shopsphere-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: shopsphere-backend

  template:
    metadata:
      labels:
        app: shopsphere-backend

    spec:
      containers:
        - name: backend
          image: shopsphere-backend:v2

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
           
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: shopsphere-backend-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: shopsphere-backend-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: shopsphere-backend-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: shopsphere-backend-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopsphere-backend-secret
                  key: DB_PASSWORD
