apiVersion: v1
kind: Secret

metadata:
  name: shopsphere-db-secret

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: rootpassword123
  MYSQL_DATABASE: shopsphere
  MYSQL_USER: shopsphere
  MYSQL_PASSWORD: shopsphere123
