apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopsphere-frontend
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopsphere-backend
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopsphere-database
automountServiceAccountToken: false
