# Core Kubernetes API
apiVersion: v1

# Resource type
kind: Secret

# Secret information
metadata:
  name: db-secret

# Default secret type
type: Opaque

# Plain text values (Kubernetes encodes them)
stringData:
  username: admin
  password: SuperSecret123