apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopsphere-prod

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: backend-replicas-patch.yaml
  - path: ingress-host-patch.yaml
